# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SWIFTUI STUDY' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SWIFTUI STUDY
  pod 'SVGKit'

  target 'SWIFTUI STUDYTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SWIFTUI STUDYUITests' do
    # Pods for testing
  end

end
